name: build and push to private registry

on:
  push:
    branches:
      - main


jobs:
  build-and-push:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "=1.20"

      - name: OIDC token
        id: docker_oidc
        uses: docker/oidc-action@96ba694c64860c7209bcd1ede7d698c71564ef78 # v1.2.0
        with:
          connection-id: ${{ secrets.DOCKER_OIDC_ID }}

      - name: Docker OIDC login
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: rocketchat
          password: ${{ steps.docker_oidc.outputs.token }}

      - uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}
          platforms: linux/amd64
          push: true
          tags: rocketchat/redis-backup-sidecar:${{github.sha}}
