name: build and push to private registry

on:
  push:
    branches:
      - main


jobs:
  build-and-push:
    if: false
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "=1.20"
          
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERREGISTRY_USERNAME }}
          password: ${{ secrets.DOCKERREGISTRY_PASSWORD}}

      - uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}
          platforms: linux/amd64
          push: true
          tags: rocketchat/redis-backup-sidecar:${{github.sha}}
